### ISSUE TITLE
Add option to specify 'aliases' file location

### ISSUE THREAD

**Issue by rfgamaral** [firstandthird/load-grunt-config#109]
I really like the flexibility of this library allowing me to break up my Gruntfile into multiple and more maintainable files. For me, there's only one thing missing and that's the option to specify the `aliases` file location.

Why would I want this? Well... I like to separate my custom tasks implementation from my tasks configurations and for that I use `load-grunt-config` like this:

``` javascript
require('load-grunt-config')(grunt, {
    jitGrunt: {
        customTasksDir: path.join(process.cwd(), 'grunt/tasks')
    },
    configPath: path.join(process.cwd(), 'grunt/options')
});
```

With this configuration, I'm forced to have the `aliases` file inside the `grunt/options` folder, which doesn't make much sense to me. It would make more sense to have it in the `grunt/tasks` folder instead. Or, my preferred option, the root `grunt` folder as to not mix up with **custom tasks** and **tasks configuration**.

**Comment by rarila** [comment]
:+1:

**Comment by AleksueiR** [comment]
:+1:

**Comment by GawainLynch** [comment]
:+1:

**Comment by jgallen23** [comment]
good idea.  I'll accept a PR if anybody wants to tackle it
