### ISSUE TITLE
Question: How to keep part of the overridden tasks. 

### ISSUE THREAD

**Issue by brunano21** [firstandthird/load-grunt-config#123]
Hi all,

Let's start saying I'm into a multi project folder, where each folder contains css, js, html files.
The folder structure is almost the following:

    + root\
        + .grunt\
            - jshint.js
        + js\
        + css\
        + app1\
            + .grunt\
                jshint.js
            + js\
            + css\
            - Gruntfile.js
        + app2\
            + .grunt\
                jshint.js
            + js\
            + css\
            - Gruntfile.js

Basically, I'm using this plugin to override the shared and common tasks as following: (from app1\Gruntfile.js)

    var options = {
        configPath: path.join(process.cwd(), '..', '.grunt'),
        overridePath: path.join(process.cwd(), '.grunt'),
        init: true,
        data: {
        },
        ...
        ...
    };

With the above code (as explained into the documentation) I'll load the "shared" grunt tasks which live under root/.grunt/ and if then a certain task (let's say root\app1\.grunt\jshint.js for example) exists, the `jshint` task will be overridden. That's really awesome! 
However, I would like to keep the original `src` files of the "shared" jshint task (root\.grunt\jshint.js), and add a **supplementary** `src` folders set defined into the `jshint` subtask (root\app1\.grunt\jshint.js).
How may I sort that out?
Thanks!

**Comment by SolomoN-ua** [comment]
Hi @brunano21,
if I correctly understand your question then you can use ```postProcess``` functionality (or ```mergeFunction```, ```preMerge```).

**Comment by brunano21** [comment]
Could you provide an example? Even not working.
Thanks.

**Comment by SolomoN-ua** [comment]
Example from [documentation](https://github.com/firstandthird/load-grunt-config#example).
```js
    require('load-grunt-config')(grunt, {
    //can post process config object before it gets passed to grunt
    postProcess: function(config) {},

    //allows to manipulate the config object before it gets merged with the data object
    preMerge: function(config, data) {}
});
```

so in case of ```posProcess``` you will get result config as an function param, and you can change any data in it before it will be passed to grunt.

**Comment by brunano21** [comment]
Well, 
I found a possible solution, different from your: 
    
    var options = {
        configPath: path.join(process.cwd(), '.grunt', 'tasks'),
        init: true,
        data: {
            sharedConfig: grunt.file.readJSON(path.join(process.cwd(), '..', '.grunt' ,'config.json')),
            componentConfig: grunt.file.readJSON(path.join(process.cwd(), '.grunt' ,'config.json')),
        },

        jitGrunt: {
            pluginsRoot: '../node_modules',
            staticMappings: {
                availabletasks: 'grunt-available-tasks'
            },
        },
    };
    require('load-grunt-config')(grunt, options);

And then in my `less.js` task:

    module.exports = function (grunt, options) {

        var path = require('path');
        var projectRoot = options.sharedConfig.cirrusRoot;
        var lessSrc = options.sharedConfig.bowerComp.lessSrc;
        var lessFiles = [];

        // loading shared less files into lessFiles array
        lessSrc.forEach(function(filePath) {
            lessFiles.push(path.join(projectRoot, filePath));
        });

        // loading component less files into lessFiles array
        lessFiles.push(options.componentConfig.resources.css);

        return {
            development: {
                files: [
                    {
                        expand: true,
                        cwd: ".",
                        src: lessFiles,
                        ext: ".css"
                    }
                ]
            }
        };
    };

I know this is not best solution, but what you think?

**Comment by SolomoN-ua** [comment]
Another option, you can pass original ```src``` as ```data: {}``` and then you it in subtasks.
For example:
```js
// load-grunt-config
data: {
    shared: {
        jshint: {
            src: '../../..'
        }
    }
}

// in task config
{
   src: '<%= shared.jshint.src %>'
}
```

**Comment by SolomoN-ua** [comment]
@brunano21 we had similar idea at the same time ;)

**Comment by brunano21** [comment]
Lol. In my case I'm using a config.json file containing the configuration stuff I want to share. However yep, we had the same idea :8ball:

**Comment by SolomoN-ua** [comment]
It actually doesn't matter how you will pass it to ```data: {}``` object. :)
