### ISSUE TITLE
Grunt --help does not show loaded tasks.

### ISSUE THREAD

**Issue by brunano21** [firstandthird/load-grunt-config#124]
Hi,

I'm using the plugin with the following configuration:

    var options = {
        configPath: path.join(process.cwd(), '.grunt', 'tasks'),
        init: true,
       
        data: {
            sharedConfig: grunt.file.readJSON(path.join(process.cwd(), '..', '.grunt' ,'config.json')),
        },
        // using jitGrunt instead of the built-in loader.
        jitGrunt: {
            pluginsRoot: '../node_modules',
            staticMappings: {
            },
        },
    };
    require('load-grunt-config')(grunt, options);

But unfortunately, running `grunt --help`, it does not list all loaded tasks I have in `.grunt\tasks` folder.
Am I missing something?

**Comment by SolomoN-ua** [comment]
Hi @brunano21,
I think that's how [jit-grunt](https://github.com/shootaroo/jit-grunt) works.
Task is loaded only when it is needed/requested.

**Comment by brunano21** [comment]
@SolomoN-ua quick reply! :+1: 
So, unless we use the `aliases` file, we could say there is not a way to list all tasks available. Right?

**Comment by SolomoN-ua** [comment]
@brunano21 
Right, because we are not loading/registering them just to save some execution time.

**Comment by brunano21** [comment]
So in these conditions, the `grunt-available-tasks` plugin is basically useless.

**Comment by SolomoN-ua** [comment]
Yep, the only way to make it work with ```jit-grunt``` is just use aliases.
(or switch to default ```load-grunt-tasks```)

**Comment by brunano21** [comment]
Let's suppose I want for a moment to forget of `jit-grunt`, commenting its code from above. Now running grunt I get error like: `Local Npm module "grunt-contrib-jshint" not found. Is it installed?`. Is this related to the fact that the node_modules lives in another directory (`..\` - have a look to the jit-grunt configuration of the code above)?

**Comment by SolomoN-ua** [comment]
You can pass configuration to ```load-grunt-tasks``` using ```loadGruntTasks: {}``` object.
More about ```load-grunt-tasks``` configuration you can find [here](https://github.com/sindresorhus/load-grunt-tasks).

**Comment by brunano21** [comment]
I do not understand how they fit together :/

**Comment by brunano21** [comment]
Ok, I installed the `load-grunt-tasks` plugin and provided the `loadGruntTask: {}` obj through the load-`grunt-config` options, however, I'm getting always the same error.

**Comment by szarouski** [comment]
You can still use jit grunt and get performance boost if you do something like:

```js
module.exports = function (grunt) {
    var path = require('path');
    var isHelpMode = grunt.option('help');
    // require('time-grunt')(grunt);
    var config = {
        configPath: path.join(process.cwd(), 'node_configs')
    };

    if (isHelpMode || process.env.GRUNT_LOAD_ALL_TASKS) {
        config.loadGruntTasks = {
            pattern: 'grunt-*',
            config: require('./package.json'),
            scope: ['dependencies', 'devDependencies', 'archivedDependencies']
        };
    } else {
        config.jitGrunt = {
            customTasksDir: './node_tasks',
            staticMappings: {
                scsslint: 'grunt-scss-lint'
            }
        };
    }

    require('load-grunt-config')(grunt, config);
};
```
