### ISSUE TITLE
Grunt can't reference underscore/lodash and tasks break

### ISSUE THREAD

**Issue by JeSuis** [firstandthird/load-grunt-config#126]
With normal grunt setup I had this at the top of my grunt file which gets used in settings for tasks.
`var _ = require('underscore');`

After changing the setup as per instructions I get the error.
`>> ReferenceError: _ is not defined`

And it breaks all the tasks.
The var gets set but I haven't been able to successfully pass it in.

It's not really specific to underscore/lodash, would happen with setting any var for use in any task.

**Comment by SolomoN-ua** [comment]
Hi @JeSuis, you just need to add this line ```var _ = require('underscore');``` in all task files, where you are using underscore. :)

**Comment by JeSuis** [comment]
ah I was hoping to not to have to do that to keep it dry, o well, thanks for your reply!

**Comment by SolomoN-ua** [comment]
unfortunately that's how javascript works :(

**Comment by matt-bailey** [comment]
Hi, I'm having a similar issue and wondered if you could give some example code? For example, take this standard Grunt task config (when not using load-grunt-config):

```javascript
var compass = require('compass-importer');
grunt.initConfig({
    sass: {
        options: {
            importer: compass
        },
        ...        
    }
})
```

If I were using load-grunt-config with a `sass.js` task file, how/where would I put the `var compass = require('compass-importer');` line?

**Comment by SolomoN-ua** [comment]
Hi @matt-bailey,

```js
// sass.js file:
var compass = require('compass-importer');

module.exports = {
    options: {
        importer: compass
    },
    ...
};
```

I think something like this should work.

**Comment by matt-bailey** [comment]
Thanks for getting back to me @SolomoN-ua. I was hoping it would be that simple, but I'd already tried that and it didn't work.

When I ran the task in debug mode I could see that in the Options object `importer=undefined`. Let me know if you have any other thoughts.

**Comment by SolomoN-ua** [comment]
First of all check if `compass-importer` is installed and please provide your `Gruntfile.js`, `sass.js` files. It will be hard to investigate problem without this files.

**Comment by cristinallamas** [comment]
Hi, did you fix this issue? if so , could you share it? I found the same problem
