### ISSUE TITLE
Request update dependencies for grunt 0.4.5

### ISSUE THREAD

**Issue by dsoldera** [firstandthird/load-grunt-config#127]
Hi,

Please update the load-grunt-config dependencies for Grunt 0.4.5.

Please check the print screenshot attached,

Thanks and regards

Danielle
![issue-grunt-load-config](https://cloud.githubusercontent.com/assets/11474555/8461492/72fccd22-2003-11e5-942c-ca725a68cfe3.png)

**Comment by SolomoN-ua** [comment]
Hi @dsoldera, PR from @luisfmsouza #128 already merged and newer version ```0.17.2``` was published to ```npm```. Closing this issue, please reopen it if you still have a problem.
