### ISSUE TITLE
Use recent version of `load-grunt-tasks`

### ISSUE THREAD

**Issue by unindented** [firstandthird/load-grunt-config#130]
`load-grunt-tasks` is at `3.2.0`, but this project is still using `~0.3.0`.

**Comment by SolomoN-ua** [comment]
Thanks @unindented, I will update it in next release, thanks!

**Comment by weblancaster** [comment]
Hey @unindented any update on this?

**Comment by unindented** [comment]
@weblancaster doesn't look like it. Don't know if @SolomoN-ua has abandoned the project...

**Comment by SolomoN-ua** [comment]
@unindented @weblancaster I'm already here, thanks for reminder... give me few hours

**Comment by SolomoN-ua** [comment]
new version ```load-grunt-config 0.18.0``` published to npm, sorry for delay... :(

**Comment by unindented** [comment]
Awesome! Thanks @SolomoN-ua.

**Comment by weblancaster** [comment]
Yeah thanks @SolomoN-ua
