### ISSUE TITLE
Passing Regex in Config Files.

### ISSUE THREAD

**Issue by ChrisSargent** [firstandthird/load-grunt-config#133]
Hi,

I've just started using this - thanks for the effort so far. In one of my config files for 'uncss' I'm trying to use an ignore option with some Regex in it. This seems to break this plugin and make the file unreadable.

This is my config file:

```js
{
    "options": {
        "ignore": [/spx/],
        "ignoreSheets": []
    },

    "dev": {

        "files": {
            "<%= sass.dev.dest %>": ["index.html"]
        }
    },

    "build": {
        "files": {
            "<%= sass.build.dest %>": ["index.html"]
        }
    }
}
```

and eventually I will want to add a bunch of ignores in there like this: https://github.com/mpc-hc/mpc-hc.org/blob/master/Gruntfile.js#L86

Any idea how I can get this to parse properly please?

Thanks!

Chris

**Comment by SolomoN-ua** [comment]
Hi @ChrisSargent,
as I understand you are using `.json` config file type. RegExp is not a valid json data type, that's why you have a broken json file.
So you have two options use `.js` file type instead (easiest way) or use RegExp as a string field (if plugin supports it).

**Comment by ChrisSargent** [comment]
Okay, gotcha! I had a feeling overnight that might be the case, thanks!

**Comment by ChrisSargent** [comment]
That's working now, thanks for your help, I appreciate it!

**Comment by SolomoN-ua** [comment]
No problem, have a nice day! :)
