### ISSUE TITLE
Cannot register tasks

### ISSUE THREAD

**Issue by MarkusPint** [firstandthird/load-grunt-config#134]
**My Gruntfile:**

    module.exports = function (grunt) {
        grunt.file.defaultEncoding = 'utf-8';
        require('load-grunt-config')(grunt);
    };

**grunt/aliases.json:**

    {
        "dev": [
            "sass"
        ]
    }

**grunt/css.js:**

module.exports = {

    sass: {
        options: {
            loadPath: [
                'bower_components/jeet/scss/',
            ]
        },
        dist: {
            files: {
                'dist/css/main.css': __dirname + '/src/sass/index.scss'
            }
        }
    }

};

Output:
>> No "sass" targets found.
Warning: Task "sass" failed. Use --force to continue.

Aborted due to warnings.

What is wrong? I tried to follow the examples I found 1:1

**Comment by SolomoN-ua** [comment]
Hi @MarkusPint, in this case file should be named ```grunt/sass.js``` not ```grunt/css.js```. For example:
```js
// grunt/sass.js
module.exports = {
    options: {
        loadPath: [
            'bower_components/jeet/scss/',
        ]
    },
    dist: {
        files: {
            'dist/css/main.css': __dirname + '/src/sass/index.scss'
        }
    }
};
```

**Comment by MarkusPint** [comment]
Hi, thanks for the swift response.

I am still not fully clear on how this has to work.

Is the intended usage 1 task per file?

**Comment by SolomoN-ua** [comment]
You have two options:
1. [one file per task](https://github.com/firstandthird/load-grunt-config#grunt-tasks-files) (with multiple targets config in it), in this case file name is task name
```js
// example: grunt/clean.js
module.exports = {
    js: { ... },
    css: { ... },
    ...
};

// result: clean:js, clean:css
```

2. [or one file per target](https://github.com/firstandthird/load-grunt-config#config-grouping) (with multiple tasks config in it), in this case file name is target name with suffix ```-tasks```
```js
// example: grunt/css-tasks.js
module.exports = {
    clean: { ... },
    sass: { ... },
    ...
};

// result: clean:css, sass:css
```

**Comment by SolomoN-ua** [comment]
btw, you can combine both options at the same time, but be aware not to duplicate same "task:target" combination.

**Comment by MarkusPint** [comment]
I think I got it now. Thanks alot :)

**Comment by SolomoN-ua** [comment]
np, closing issue for now, if you will still have problems let me know.
