### ISSUE TITLE
Tested against npm 3?

### ISSUE THREAD

**Issue by johnman** [firstandthird/load-grunt-config#135]
Hi,

I've decided to test npm 3 to see if there were any issues (as they have now removed the beta flag).

My setup that works fine with npm 2 now complains that it can't find task e.g. clean even though grunt-contrib-clean) exists in the root folder and clean.js still exists in my grunt folder.

Have you had a chance to look at npm 3?

**Comment by SolomoN-ua** [comment]
Hi @johnman,

I'm using ```npm  3.3.3``` and everything works just fine, can you provide more information about your configurations?

**Comment by johnman** [comment]
Yeah, sorry a configuration error while experimenting with npm 3. Moved things from peer dependencies to dependencies (to get everything installed in root node_modules.....experiment and probably won't do that as you can't guarantee the version you want will go in the root if there is a conflict) and had a custom part of the grunt script look at peer dependencies when looking at grunt modules to load.

Fixed that and it all works. So not a bug.

**Comment by Chris2011** [comment]
What is the solution of this? I don't get it, I have the same error that when I call grunt serve or grunt clean, that I get the error clean not found. I have Node 5.3.0 and npm 3.3.12.

**Comment by SolomoN-ua** [comment]
can you provide your Gruntfile?

**Comment by Chris2011** [comment]
It was my fault, everything was fine now. I had a merge conflict in a task file and forgot to remove <<<<<< HEAD. Now it works. Thx :)
