### ISSUE TITLE
Custom .js file names under grunt tasks folder

### ISSUE THREAD

**Issue by tamertemizer** [firstandthird/load-grunt-config#136]
Hello, is there a way to change file names connected to the plugins? For example if I use grunt-exec plugin I need exec.js under my grunt tasks folder. If the file's name isn't exec.js load-grunt-config won't understand it is connected to the exec plugin. However I want to have custom file names. This will allow me to use more descriptive names and remind me why I use that plugin.

**Comment by SolomoN-ua** [comment]
Hi @tamertemizer,

there is no way to rename task config files, but you can use [config grouping](https://github.com/firstandthird/load-grunt-config#config-grouping) instead.

**Comment by SolomoN-ua** [comment]
Hi @tamertemizer,

one week without response, so I'm closing this issue for now, feel free to reopen if you have more questions.

**Comment by tamertemizer** [comment]
Hi @SolomoN-ua,

I'm trying to use the config grouping. I tried with js and yaml but no luck. 

My config file for jsdoc (jsdoc.yaml) is this. This one works as expected.

dist:
    src: 'src/**/*.js'
      options:
        destination: 'dist/doc'
        template: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template'
        configure: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json'

My config file after the grouping is this(documents-tasks.yaml). 

jsdoc:
  dist:
    src: 'src/**/*.js'
    options:
      destination: 'dist/doc'
      template: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template'
      configure: 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/jsdoc.conf.json'

This doesn't work. I get this error message

Warning: Cannot read property 'dest' of undefined Use --force to continue.

Do you have any idea?

**Comment by SolomoN-ua** [comment]
Unfortunately I'm not familiar with YAML but with JSON you can try something like this:
```json
// documents-tasks.json file content:
{
  "jsdoc": {
    "src": "src/**/*.js",
    "dist": "write something here",
    "options": { }
  }
}
```

**Comment by tamertemizer** [comment]
I still have the same error with json. Do I need to change something in aliases file to allow grouping? Jsdoc part of my aliases file is this: 

'doc-files' : ['jsdoc'],

**Comment by SolomoN-ua** [comment]
try running ```grunt --config-debug``` and can you provide your ```Gruntfile.js```?

**Comment by SolomoN-ua** [comment]
btw, just noticed... when you using ```*-tasks.(js|json|etc.)``` file content should be like this
```js
module.exports = {
    jsdoc: {
        src: '...'
    }
}
```
not like this
```js
module.exports = {
    jsdoc: {
        target: { // or in your case dist
            src: '...'
        }
    }
}
```

**Comment by tamertemizer** [comment]
Oh god! Thanks it works now! I really appreciate the support. Thank you very much!

**Comment by SolomoN-ua** [comment]
No problem, feel free to ask if you will have some other questions! :)
