### ISSUE TITLE
Not able to run load-grunt-config with jshint and customtask 

### ISSUE THREAD

**Issue by jforjava1981** [firstandthird/load-grunt-config#142]
Can you please help me what I am missing in configuration mentioned in below SO question : 

http://stackoverflow.com/questions/33854582/task-not-found-when-grunt-is-run-using-load-grunt-config

I didn't repeat the whole content just to keep it at one place, I am sure I am not understanding how it all works.

**Comment by SolomoN-ua** [comment]
where is your test task code?

P.S.: My suggestion, first of all try to make it work without `load-grunt-config`...

**Comment by jforjava1981** [comment]
code for test task? its in test.js as follows : 

  module.exports = {
    test :{
        local : {
        }
    }
 };

I guess I am missing very basic thing.

**Comment by SolomoN-ua** [comment]
This is configuration for task, not task itself. To get more detailed info please read official Grunt documentation first http://gruntjs.com/getting-started.

Closing this issue for now, as it is not connected with functionality of `load-grunt-config`. Feel free to open new issue if you will have problems with `load-grunt-config` functionality. :)
