### ISSUE TITLE
No support for arrays in "configPath" (since 0.19.0)

### ISSUE THREAD

**Issue by tschoenti** [firstandthird/load-grunt-config#143]
Starting with 0.19.0, arrays for the configPath property doesn't work.

```javascript
{
configPath: "/home/foo/bar/grunt"
}
```
works, 
but 
```javascript
{
configPath: ["/home/foo/bar/grunt"]
}
```
leads to the following error:
```javascript
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'Gruntfile.js'
Grunt: The JavaScript Task Runner (v0.4.5)
```

In 0.18.0 | 0.17.2 | 0.17.1 both variants (arrays of strings / single string) works perfectly.

**Comment by SolomoN-ua** [comment]
Hi @tschoenti, PR https://github.com/firstandthird/load-grunt-config/pull/141 should fix this problem. I'm testing it right now and will publish fixed version soon.

**Comment by SolomoN-ua** [comment]
@tschoenti new version `0.19.1` is published to npm.
Have a nice day.

**Comment by tschoenti** [comment]
That's fast service. Thank!

Von meinem iPhone gesendet
