### ISSUE TITLE
Async Config Loading

### ISSUE THREAD

**Issue by lzilioli** [firstandthird/load-grunt-config#144]
I want to asynchronously generate the configs for one of my grunt tasks. Is this possible using load-grunt-config? Looking at how the config files are read in, it appears to not be the case. https://github.com/firstandthird/load-grunt-config/blob/master/lib/readconfigdir.js#L24

Any opposition/thoughts around extending the supported API of the exported function to return its config asynchronously?

**Comment by SolomoN-ua** [comment]
Hi @lzilioli, you can use ```postProcess: function(config) {}``` functionality for extending ```config``` object with your asynchronously generated configurations.

**Comment by SolomoN-ua** [comment]
As far as I know Grunt configuration should be initialized before Grunt will execute any task. If you need to change it during tasks execution you will need to do it manually by using [grunt.config API](http://gruntjs.com/api/grunt.config).

**Comment by SolomoN-ua** [comment]
Hi @lzilioli, can you provide any feedback?

**Comment by SolomoN-ua** [comment]
Hi @lzilioli, closing this issue for now. Let me know if you still have problems.
