### ISSUE TITLE
Do aliases have reserved words or what is going on?

### ISSUE THREAD

**Issue by deiga** [firstandthird/load-grunt-config#145]
Some aliases are resolved as `undefined` for some reason, and it only seems to hit certain words. If I change alias names then they work.
Currently I've got `ci` and `local` aliases, which both don't work.
https://gist.github.com/1909bffee4b79e98cb43

**Comment by jgallen23** [comment]
can you run grunt with `--config-debug` and paste that in here?

**Comment by deiga** [comment]
https://gist.github.com/deiga/e03e218e20d87517ab7b

**Comment by jgallen23** [comment]
@deiga very odd.  it looks like ci and local are registering fine.  What does grunt output when you type in `grunt ci`?

**Comment by deiga** [comment]
@jgallen23  This is very odd..

https://gist.github.com/deiga/2f752f1b33c0e202238a

**Comment by deiga** [comment]
Really really odd, `ci` began working, but `local` still doesn't work. On top of that `release` and `production` doesn't work and one task `cachebust` doesn't work either :/

**Comment by jgallen23** [comment]
@deiga can you run all of the ci tasks individually?

**Comment by deiga** [comment]
@jgallen23 Yes, I can. But each one prints out that Error where some aliases seem to be undefined...
