### ISSUE TITLE
How does one share values between tasks?

### ISSUE THREAD

**Issue by deiga** [firstandthird/load-grunt-config#146]
I have a destination path for all my builds and I want it to come from a variable. How can I create a variable that all my tasks see?

**Comment by SolomoN-ua** [comment]
Hi, you can define it in `data: {}` property
```js
require('load-grunt-config')(grunt, {
    ...
    data: {
        someVar: 42,
        otherVar: {
            foo: 'some/path'
        }
    }
    ...
});
```
and then use it in any config string like `'<%= someVar %>'` and `'<%= otherVar.foo %>'`, also the same way you can access to any other config properties (for example `'<%= copy.app.dest %>'`)

**Comment by deiga** [comment]
Thank you! Maybe add this to the readme? :)

**Comment by SolomoN-ua** [comment]
it is in readme, in some way :)
but maybe I will try to improve it...

**Comment by SolomoN-ua** [comment]
@deiga let me know if you will have other issues.
Have a nice day!
