### ISSUE TITLE
aliased tasks not found

### ISSUE THREAD

**Issue by bolera** [firstandthird/load-grunt-config#147]
I'm sorry, but I'm probably missing something obvious. I tried to follow several tutorials and your documentation. They *all* fail at this point: the target task specfied in the aliases.js file is not found. Already posted this question on stackoverflow: 
http://stackoverflow.com/questions/35712402/load-grunt-config-not-finding-target-task
This is definitely the first time that any kind of tutorial for any kind of programming does not work for me. I'm at a loss. Evern following this very simple approach gives me the same result: http://www.html5rocks.com/en/tutorials/tooling/supercharging-your-gruntfile/
I have files aliases.js and testtask.js in the grunt directory, but testtask is not found from aliases.
What could be the cause?
(In all other aspects gruntjs seems to be doing fine, e.g. the original, very long gruntfile works just fine.)

**Comment by SolomoN-ua** [comment]
Hi, you have few mistakes in your config.
Should be like this:
```js
// testtask
module.exports = {
  copy: {
        files: 
        [{
           src:  "test1.txt",
           dest: "test2.txt"
        }]
  }
};
```
and
```js
// aliases
module.exports = {
  'default': [],
  'mytesttask': [
    'copy:testtask'
  ]
};

**Comment by SolomoN-ua** [comment]
Please note, that if you want to create `testtask` target for `copy` task (grunt-contrib-copy), then your file should be named `copy.js`!

**Comment by SolomoN-ua** [comment]
@bolera closing this issue for now, please fill free to reopen if you will have any technical problems!

**Comment by bolera** [comment]
Thank you for the hint. Yes, in the mean time after reading yet another tutorial (http://mattbailey.io/a-beginners-guide-to-grunt-redux.html) I finally understood that I have to group all the various tasks in a file that is named after the grunt module. I was rather coming from the view that I want to split by "virtual task" and have a copy section in each of them. Might be worthwhile to clearly point out in the documentation that the various task files have to be named after the grunt module. At least that is what I didn't get until now. Once I understood that it's working just fine.

**Comment by johnjspiteri** [comment]
@SolomoN-ua, I hit a brick wall when having "jit-grunt" in my package.json, which prevented the "default" task to be loaded... maybe we could specifically add a warning in the docs?
