### ISSUE TITLE
Can't use config variables in aliases

### ISSUE THREAD

**Issue by curtisblackwell** [firstandthird/load-grunt-config#150]
The config variables are working fine elsewhere, so I know they're loading properly, but with the below setup, I'm getting an error.

### `Gruntfile.js`
```js
var mrPig = grunt.file.readYAML('mr_pig/settings.yaml');

require('load-grunt-config')(grunt, {
  configPath: path.join(process.cwd(), 'mr_pig/core/tasks'),
  overridePath: 'mr_pig/tasks',
  config: {
    m: mrPig
  }
});
```

### `mr_pig/settings.yaml`
```yaml
default:
  - serve
```

### `mr_pig/core/tasks/aliases.yaml`
```yaml
default:
  tasks: '<%= m.default %>'
```

### Error message from running `grunt`
```sh
Running "default" task
Warning: Task "<%= m.default %>" not found. Use --force to continue.

Aborted due to warnings.
```

---

Should I be able to use the config variables in `aliases.yaml`?

**Comment by SolomoN-ua** [comment]
Hi @curtisblackwell, as far as I know templates are not supported in Grunt `registerTask`, only in `initConfig`. So unfortunately you are not able to use templates in `aliases` because it uses Grunt `registerTask` inside. :(

**Comment by curtisblackwell** [comment]
Ah, got it. Thanks!
