### ISSUE TITLE
Update jit-grunt dependency

### ISSUE THREAD

**Issue by martiell** [firstandthird/load-grunt-config#152]
Please update the version of jit-grunt specified in the package.json.

The current version listed in package.json is ~0.9.1 and the latest version is 0.10.0.

jit-grunt 0.9.1 specifies grunt ~0.4.0 as a peerDependency:

    "peerDependencies": {
      "grunt": "~0.4.0"
    },

This has been fixed to allow use of grunt 1.0.x in jit-grunt 0.10.0:

https://github.com/shootaroo/jit-grunt/commit/08850b46409c16dd12ad1fd97aa12bdab331b465

It seems possible to install grunt 1.0.1 alongside load-grunt-config 0.19.1, but npm shrinkwrap fails complaining about jit-grunt's peerDependencies.

Thanks.

**Comment by SuneRadich** [comment]
+1

**Comment by SolomoN-ua** [comment]
Hi guys, I will publish new version soon.

**Comment by SolomoN-ua** [comment]
Hi guys, new version was published to npm
