### ISSUE TITLE
Private tasks in aliases.yaml

### ISSUE THREAD

**Issue by freefri** [firstandthird/load-grunt-config#155]
Is there any way to set tasks as private in the aliases.yaml file?
See [https://github.com/gruntjs/grunt/issues/741](https://github.com/gruntjs/grunt/issues/741)

Maybe there is some workaround possible.

**Comment by SolomoN-ua** [comment]
Hi @freefri, if there is no way to do it in Grunt then there is no way to do it with `load-grunt-config`. But if you have an idea how this can be implemented please just provide a PR :)
