### ISSUE TITLE
Access to "data" with `grunt.config.get()`

### ISSUE THREAD

**Issue by danosaure** [firstandthird/load-grunt-config#158]
I'm trying to have access to a value i set in the `data` section:

    loadGruntConfig(grunt, {
        ...,
        data: {
            packageJson: require('./package.json')
        }
    });

in one of my   grunt/config/file.js:

    module.exports = (grunt) => {
        console.log("grunt.config.get():", grunt.config.get());
    };

will yield and empty object. Is there anyways for this to work?  (I cannot use, in my context, the `<%= packageJson.version %>` that I need.)

**Comment by wardpeet** [comment]
you have 2 arguments grunt, options. Options should contain the package.json info

**Comment by danosaure** [comment]
What is `data`? Can you show me an example. Given above `data`, I am able to use that variable, but unable to retrieve it from the `grunt.config.get()`.

**Comment by wardpeet** [comment]
`module.exports = (grunt, options) => {
    console.log("grunt.config.get():", grunt.config.get());
    console.log("options:", options);
};`

**Comment by danosaure** [comment]
awesome, thanks. I should have checked with `arguments`. My bad.
