### ISSUE TITLE
Working with scoped packages

### ISSUE THREAD

**Issue by monolithed** [firstandthird/load-grunt-config#162]
### Problem

```js
{
		configPath: 'tasks',

		jitGrunt: {
			staticMappings: {
				'foo': '@bar/foo'
			}
		}
}
```

[Scoped packages](https://docs.npmjs.com/misc/scope) are used for a long time. It seems you should support them.

**Comment by SolomoN-ua** [comment]
Hi @monolithed, please address this issue to [https://github.com/shootaroo/jit-grunt](jit-grunt) project, `jit-grunt` static mappings is not a part of `load-grunt-config`.

**Comment by monolithed** [comment]
@SolomoN-ua, why do you think so? Generally, I don't want to use `jitGrunt` in my config

**Comment by SolomoN-ua** [comment]
@monolithed in your example you are showing the part which is responsible for `jit-grunt` configuration, if you don't want to use `jit-grunt` switch to `load-grunt-tasks` just by removing the whole `jitGrunt: {}` block from your config file, or by replacing it with `jitGrunt: false`.

**Comment by monolithed** [comment]
```
jit-grunt: Plugin for the "foo" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "foo" failed. Use --force to continue.
```

How to avoid static mappings for scoped packages?

**Comment by monolithed** [comment]
Oh, sorry, `jitGrunt: false` is working fine

**Comment by SolomoN-ua** [comment]
if you are using `jit-grunt` (as I can see), please ask this question in [jit-grunt](https://github.com/shootaroo/jit-grunt) project, as `load-grunt-config` not using this configuration internally, it's only passing this configuration to `jit-grunt` library.

P.S.: `load-grunt-config` only responsible for configuration files, task loading is part of `load-grunt-tasks` or `jit-grunt` (depends on your configuration)

**Comment by SolomoN-ua** [comment]
@monolithed no problem, have a nice day :)
