### ISSUE TITLE
>> ReferenceError: grunt is not defined

### ISSUE THREAD

**Issue by Memanoth** [firstandthird/load-grunt-config#171]
Hi

I was just wondering if this still works?
I followed this guide (http://mattbailey.io/a-beginners-guide-to-grunt-redux.html) to the letter and for some reason I constantly get a ">> ReferenceError: grunt is not defined" error. Any assistance would be great.

Thanks,
Andrew

**Comment by SolomoN-ua** [comment]
@Memanoth if you still have a problem, feel free to reopen this issue. Closing it for now.
