### ISSUE TITLE
JS-YAML update, high severity vulnerability

### ISSUE THREAD

**Issue by cakasuma** [firstandthird/load-grunt-config#179]
when i run npm audit, i found the following error

High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ load-grunt-config [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ load-grunt-config > js-yaml                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813 

can we please update the package..

**Comment by cakasuma** [comment]
i just saw it has been addressed. when will be the release of 1.0.2 ?

**Comment by SolomoN-ua** [comment]
Done
