### ISSUE TITLE
dependency js-yaml update, high severity vulnerability

### ISSUE THREAD

**Issue by tzahari** [firstandthird/load-grunt-config#180]
Please update js-yaml cause npm audit found this issue:

`┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ load-grunt-config [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ load-grunt-config > js-yaml                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/788                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ load-grunt-config [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ load-grunt-config > js-yaml                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
`
Thank you

**Comment by Nnamdi101** [comment]
It looks like this is fixed in version `2.0.0-rc1`. Does anyone know when this will be released?

**Comment by SolomoN-ua** [comment]
Package version `2.0.0-rc1` is already available on npm repo.

**Comment by SolomoN-ua** [comment]
Btw, also just published two new versions:
2.0.0 - release version instead of RC1
3.0.0-rc1 - RC version with newer load-grunt-tasks and support of Node >= 8
