### ISSUE TITLE
Allow relative path for JS loading

### ISSUE THREAD

**Issue by zypA13510** [firstandthird/load-grunt-config#183]
When I split my config into tasks folder, using a js config file, the following error is shown:
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'tasks/postcss.js'
```
However, this does not seem to affect yaml configs.

After looking into this using `node --inspect`, the culprit seems to be [this](https://github.com/firstandthird/load-grunt-config/blob/e5f90e3fb838ee6356407fa2946eaac2e638a000/lib/readfile.js#L28):
```Javascript
    // JS / JSON / CoffeeScript
    if (ext.match(/json|js|coffee|ls/)) {
        return require(file);
    }
```
Obviously, "require" without "./" makes node mistake the file name as a module name.
The correct syntax should be ``require(`./${file}`)`` if the path is relative.

Fixing this should be easy, I will provide a patch soon.

**Comment by SolomoN-ua** [comment]
Thanks, will publish new version a bit later today.

**Comment by zypA13510** [comment]
> will publish new version a bit later today.

@SolomoN-ua Just a friendly reminder :smiley:

**Comment by SolomoN-ua** [comment]
> > will publish new version a bit later today.
> 
> @SolomoN-ua Just a friendly reminder 😃

omg.
Sorry, crazy week at work, it is done now. Thank you for the reminder.
