### ISSUE TITLE
clean.server missing?

### ISSUE THREAD

**Issue by reintroducing** [firstandthird/load-grunt-config#40]
I've got a clean task and in it I have the following:

```
module.exports = function(grunt) {
    return {
        dist: [
            '.tmp',
            '<%= yeoman.dist %>/*'
        ],
        server: ['.tmp'],
        cq: {
            src: [
                '<%= yeoman.cq %>/css',
                '<%= yeoman.cq %>/images',
                '<%= yeoman.cq %>/js'
            ],
            options: {
                force: true
            }
        },
        hooks: {
            src: ['../.git/hooks/pre-commit'],
            options: {
                force: true
            }
        }
    }
};
```

load-grunt-config acknowledges the clean task but when i run a task that uses clean:server (or just grunt clean:dist or any other for that matter) I see this:

Running "clean:server" (clean) task
Verifying property clean.server exists in config...ERROR

Any idea why I'm getting this?  Thanks in advance.

**Comment by lpaulger** [comment]
I'm seeing this too; could you provide your solution?

**Comment by lpaulger** [comment]
I fixed this, it was caused by still having grunt.initConfig in my gruntile
