### ISSUE TITLE
Doesn't work grunt-contrib-watch.

### ISSUE THREAD

**Issue by suprahfly** [firstandthird/load-grunt-config#49]
First time tried to split my <code>Gruntfile</code> into pieces, and pretty much it all works except <code>grunt-contrib-watch</code>, and that's a bummer. 

This is my <code>watch.js</code> file:

<pre>
module.export = {
    sass: { 
        files: ['**/*.scss'], 
        tasks: ['sass', 'autoprefixer', 'cssmin']
    }
};
</pre>

And <code>aliases.yaml</code>

<pre>
default:
  - 'sass'
</pre>

And this is what I instantly get
![watchjs](https://f.cloud.github.com/assets/6453510/2515826/4d4b4ea6-b447-11e3-977b-5b8923cbac5b.JPG)

If I change <code>Gruntfile</code> to my all-in-one version (which is share the same code), it works normal.

Any ideas?)

P.S. <code>grunt</code> command without <code>watch</code> task in <code>aliases</code> works flawlessly, of course

**Comment by brunano21** [comment]
@suprahfly could you provide your solution? since I'm getting the same error. Thanks!
