### ISSUE TITLE
Help with config in a task file

### ISSUE THREAD

**Issue by richarth** [firstandthird/load-grunt-config#84]
Hi,

I've got the following Grunt file:

module.exports = function (grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
  });

  require('load-grunt-config')(grunt);
};

I've defined a file for configuring one of my tasks and I'm trying to read variables from the package file.  My task file is as follows:

module.exports = function (grunt) {
    grunt.log.writeln(grunt.config("pkg.srcSassDirectory"));
    return {
        dev: {
            options: {
                sassDir: '<%= grunt.config("pkg.srcSassDirectory") %>',
                cssDir: 'css',
                environment: 'development',
                watch: true,
                specify: 'src/sass/styles.scss'
            }
        },
        prod: {
            options: {
                sassDir: 'src/sass',
                cssDir: 'css',
                environment: 'production',
                specify: 'src/sass/styles.scss',
                outputStyle: 'compressed'
            }
        }
    }
};

The correct value for srcSassDirectory in my package file is output to the console but when I run in verbose mode I can see that sassDir is empty, just "".

How do I access variables from the package file in my task files?

**Comment by kyvour** [comment]
I have created new task for grunt right now. So you can use 'package' variable for the access to data from package.json. For example there is my notify task:
`module.exports = {
  css: {
    options: {
      title: '<%= package.name %>',
      message: 'css build has been finished'
    }
  },
};`

And there is my Gruntfile.js:
`
var path = require('path');
module.exports = function (grunt) {
  require('time-grunt')(grunt);
  require('load-grunt-config')(grunt, {
    configPath: path.join(process.cwd(), 'grunt'),
    jitGrunt: {}
  });
};
`

As you can see the 'package' variable is available automatically. This notified in readme in the Features section, but I didn't see this first time too :)

For the additional data you should use exposed options as described SolomoN-ua

P.S. Sorry for my bad English =)
