### ISSUE TITLE
Option for grunt.registerMultiTask

### ISSUE THREAD

**Issue by atav32** [firstandthird/load-grunt-config#98]
If there isn't already a way to use [`registerMultiTask`](http://gruntjs.com/api/grunt.task#grunt.task.registermultitask) instead of `registerTask`, then it'd be a nice thing to add. It could clean up the aliases file significantly.

**Comment by SolomoN-ua** [comment]
Hi @atav32, is this still an issue for you?

**Comment by atav32** [comment]
Nope
